import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";
import Map from "@/components/Map";

export default function MapPage() {
  return (
    <>
      <Head>
        <title>Withdraw or Deposit ANYWHERE!!!</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map/>
    </>
  );
}
