import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";

export default function MapPage() {
  return (
    <>
      <Head>
        <title>Withdraw or Deposit ANYWHERE!!!</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h="100vh" w="100vw">
        <Text>Hello</Text>
      </Box>
    </>
  );
}
